from __future__ import annotations

"""Utility functions for compiling C++ sources.

This module provides a thin wrapper around ``g++`` or ``clang++``
invocations. It captures diagnostics so that later phases can integrate
warning and error counts into reward shaping or reporting pipelines.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence
import shutil
import subprocess

from utils.diagnostics import Diagnostic, parse_compiler_diagnostics

# Default compile flags aimed at reasonably optimized yet deterministic
# builds. These enable common warnings to feed into diagnostics parsing.
DEFAULT_FLAGS: List[str] = [
    "-std=c++17",
    "-O2",
    "-pipe",
    "-Wall",
    "-Wextra",
    "-fdiagnostics-color=never",
]


@dataclass
class CompileResult:
    """Result of a C++ compilation command."""

    cmd: List[str]
    returncode: int
    stdout: str
    stderr: str
    warnings: List[Diagnostic]
    errors: List[Diagnostic]

    @property
    def success(self) -> bool:
        """Whether the compilation finished without errors."""

        return self.returncode == 0


def compile_cpp(
    sources: Sequence[Path],
    output: Path,
    *,
    compiler: str = "g++",
    flags: Iterable[str] | None = None,
    include_dirs: Iterable[Path] | None = None,
    lib_dirs: Iterable[Path] | None = None,
    libs: Iterable[str] | None = None,
    rpaths: Iterable[Path] | None = None,
    static: bool = False,
    use_ccache: bool = False,
) -> CompileResult:
    """Compile C++ ``sources`` into ``output`` using ``compiler``.

    Parameters
    ----------
    sources:
        Sequence of C++ source file paths to compile.
    output:
        Path to the output binary.
    compiler:
        Which compiler executable to invoke. Defaults to ``g++``.
    flags:
        Additional flags to pass to the compiler. ``DEFAULT_FLAGS`` are
        prepended automatically.
    include_dirs:
        Optional include directories passed as ``-I``.
    lib_dirs:
        Optional library search paths passed as ``-L``.
    libs:
        Optional libraries to link against (``-l<name>``).
    rpaths:
        Runtime library search paths encoded via ``-Wl,-rpath``.
    static:
        If ``True``, add ``-static`` to request a fully static binary.
    use_ccache:
        If ``True`` and ``ccache`` is available, prefix the compile command
        with it to leverage caching.
    """

    src_args = [str(Path(s)) for s in sources]
    cmd: List[str] = []
    if use_ccache and shutil.which("ccache"):
        cmd.append("ccache")
    cmd.extend([compiler, *DEFAULT_FLAGS])
    if static:
        cmd.append("-static")
    if flags:
        cmd.extend(list(flags))
    if include_dirs:
        for d in include_dirs:
            cmd.extend(["-I", str(d)])
    if lib_dirs:
        for d in lib_dirs:
            cmd.extend(["-L", str(d)])
    cmd.extend(src_args)
    if libs:
        for lib in libs:
            cmd.append(f"-l{lib}")
    if rpaths:
        for rp in rpaths:
            cmd.append(f"-Wl,-rpath,{rp}")
    cmd.extend(["-o", str(output)])

    proc = subprocess.run(cmd, capture_output=True, text=True)

    diags = parse_compiler_diagnostics(proc.stdout, proc.stderr)
    warnings = [d for d in diags if d.level == "warning"]
    errors = [d for d in diags if d.level == "error"]

    return CompileResult(
        cmd=cmd,
        returncode=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        warnings=warnings,
        errors=errors,
    )


def compile_shared_library(
    sources: Sequence[Path],
    output: Path,
    *,
    compiler: str = "g++",
    flags: Iterable[str] | None = None,
    include_dirs: Iterable[Path] | None = None,
    lib_dirs: Iterable[Path] | None = None,
    libs: Iterable[str] | None = None,
    rpaths: Iterable[Path] | None = None,
    use_ccache: bool = False,
) -> CompileResult:
    """Compile ``sources`` into a shared library ``output``.

    The produced ``.so`` can be linked into binaries generated by
    :func:`compile_cpp`.  It adds ``-shared`` and ``-fPIC`` flags and supports
    optional ``ccache`` usage to accelerate iterative builds.  ``include_dirs``,
    ``lib_dirs``, ``libs`` and ``rpaths`` mirror the parameters of
    :func:`compile_cpp` allowing shared objects with external dependencies to be
    built in a single step.
    """

    cmd: List[str] = []
    if use_ccache and shutil.which("ccache"):
        cmd.append("ccache")
    cmd.extend([compiler, *DEFAULT_FLAGS, "-shared", "-fPIC"])
    if flags:
        cmd.extend(list(flags))
    if include_dirs:
        for d in include_dirs:
            cmd.extend(["-I", str(d)])
    if lib_dirs:
        for d in lib_dirs:
            cmd.extend(["-L", str(d)])
    cmd.extend(str(Path(s)) for s in sources)
    if libs:
        for lib in libs:
            cmd.append(f"-l{lib}")
    if rpaths:
        for rp in rpaths:
            cmd.append(f"-Wl,-rpath,{rp}")
    cmd.extend(["-o", str(output)])

    proc = subprocess.run(cmd, capture_output=True, text=True)
    diags = parse_compiler_diagnostics(proc.stdout, proc.stderr)
    warnings = [d for d in diags if d.level == "warning"]
    errors = [d for d in diags if d.level == "error"]
    return CompileResult(
        cmd=cmd,
        returncode=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        warnings=warnings,
        errors=errors,
    )


def compile_static_library(
    sources: Sequence[Path],
    output: Path,
    *,
    compiler: str = "g++",
    flags: Iterable[str] | None = None,
    include_dirs: Iterable[Path] | None = None,
    use_ccache: bool = False,
) -> CompileResult:
    """Compile ``sources`` into a static ``.a`` library at ``output``.

    ``include_dirs`` behaves like the similarly named parameter of
    :func:`compile_cpp` so that headers living outside the source directory can
    be referenced during the object compilation phase.
    """

    obj_files: List[Path] = []
    stdout_parts: List[str] = []
    stderr_parts: List[str] = []
    warnings: List[Diagnostic] = []
    errors: List[Diagnostic] = []
    for src in sources:
        obj = output.with_name(Path(src).stem + ".o")
        cmd: List[str] = []
        if use_ccache and shutil.which("ccache"):
            cmd.append("ccache")
        cmd.extend([compiler, *DEFAULT_FLAGS, "-c", str(src), "-o", str(obj)])
        if flags:
            cmd.extend(list(flags))
        if include_dirs:
            for d in include_dirs:
                cmd.extend(["-I", str(d)])
        proc = subprocess.run(cmd, capture_output=True, text=True)
        stdout_parts.append(proc.stdout)
        stderr_parts.append(proc.stderr)
        diags = parse_compiler_diagnostics(proc.stdout, proc.stderr)
        warnings.extend(d for d in diags if d.level == "warning")
        errors.extend(d for d in diags if d.level == "error")
        if proc.returncode != 0:
            return CompileResult(
                cmd=cmd,
                returncode=proc.returncode,
                stdout="".join(stdout_parts),
                stderr="".join(stderr_parts),
                warnings=warnings,
                errors=errors,
            )
        obj_files.append(obj)

    ar_cmd = ["ar", "rcs", str(output)] + [str(o) for o in obj_files]
    ar_proc = subprocess.run(ar_cmd, capture_output=True, text=True)
    stdout_parts.append(ar_proc.stdout)
    stderr_parts.append(ar_proc.stderr)
    return CompileResult(
        cmd=ar_cmd,
        returncode=ar_proc.returncode,
        stdout="".join(stdout_parts),
        stderr="".join(stderr_parts),
        warnings=warnings,
        errors=errors,
    )

